// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify`, `has_ip`, `is_zero_mac`, `parse_mac`, `pick`

Future<DeviceIdInfo> getDeviceId() =>
    RustLib.instance.api.crateApiDeviceIdGetDeviceId();

class DeviceIdInfo {
  final String deviceId;
  final String adapterKind;

  const DeviceIdInfo({required this.deviceId, required this.adapterKind});

  @override
  int get hashCode => deviceId.hashCode ^ adapterKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceIdInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          adapterKind == other.adapterKind;
}
