// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `caps_lock_state`, `handle_event`, `injector_loop`, `injector_sender`, `last_error`, `map_key`, `record_error`, `run_keyboard_op`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InputEvent`

/// Arms the input injector for a new session. Idempotent.
Future<void> startInputInjection() =>
    RustLib.instance.api.crateApiInputInjectStartInputInjection();

/// Disarms the input injector - queued/incoming events are dropped instead
/// of reaching enigo until the next `start_input_injection()`. Idempotent.
Future<void> stopInputInjection() =>
    RustLib.instance.api.crateApiInputInjectStopInputInjection();

/// Fires this customer's own native copy shortcut (Cmd+C on macOS, Ctrl+C
/// elsewhere) on itself, then gives the focused app a moment to react before
/// returning. Called ONLY from the explicit "Copy from Customer" request
/// handler (producer_home_page.dart's _handleClipboardCopyRequest) — never
/// from agent-forwarded input. This is deliberately not a general Ctrl<->Cmd
/// translation of forwarded keystrokes: that would hijack e.g. a terminal's
/// Ctrl+C (SIGINT) the moment an agent typed it for an unrelated reason, with
/// no way to tell the two apart from a raw key event alone. Firing only in
/// response to an explicit, already-authorized copy request is a fundamentally
/// different (and far rarer) risk than intercepting every incidental Ctrl+C -
/// see decision.md ("Cross-Platform Copy Shortcut Handling") for the full
/// design rationale, including why transparent interception was rejected.
///
/// Reuses the injector thread/channel (constructing InputEvents directly,
/// skipping the JSON round-trip inject_input() does for agent-sourced events)
/// so this gets the same macOS main-thread handling and Enigo lazy-init-with-
/// retry as every other injected key, instead of duplicating that logic.
Future<void> pressNativeCopyShortcut() =>
    RustLib.instance.api.crateApiInputInjectPressNativeCopyShortcut();

/// Called from Dart with the raw JSON string received on the calleeRecv
/// data channel - same shape the reference Tauri app already deserializes
/// with serde, no reformatting needed on the Dart side. Returns immediately
/// (just a channel send); actual injection happens on the dedicated thread.
Future<void> injectInput({required String payloadJson}) => RustLib.instance.api
    .crateApiInputInjectInjectInput(payloadJson: payloadJson);
