// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base64_url_encode`, `decode_master_key`, `derive_connect_code`

/// 16 bytes from a CSPRNG, hex-encoded. This is the ONE thing ever persisted
/// (see lib/identity_store.dart) -- JID/password/connect code are always
/// re-derived fresh from it, never cached.
Future<String> generateMasterKey() =>
    RustLib.instance.api.crateApiPersistentIdentityGenerateMasterKey();

/// Pure function of master_key_hex -- no I/O, no randomness beyond the
/// deterministic re-derivation loop in derive_connect_code, fully
/// reproducible. Same MasterKey always produces the same DeviceIdentity.
Future<DeviceIdentity> deriveIdentity({required String masterKeyHex}) => RustLib
    .instance
    .api
    .crateApiPersistentIdentityDeriveIdentity(masterKeyHex: masterKeyHex);

class DeviceIdentity {
  final String jidLocalpart;
  final String xmppPassword;
  final String connectCode;

  const DeviceIdentity({
    required this.jidLocalpart,
    required this.xmppPassword,
    required this.connectCode,
  });

  @override
  int get hashCode =>
      jidLocalpart.hashCode ^ xmppPassword.hashCode ^ connectCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceIdentity &&
          runtimeType == other.runtimeType &&
          jidLocalpart == other.jidLocalpart &&
          xmppPassword == other.xmppPassword &&
          connectCode == other.connectCode;
}
